# Generated by Django 5.1.5 on 2025-02-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed", "-priority", "-deadline"]},
        ),
    ]
